### ISSUE TITLE
lista canales cambios a la vista

### ISSUE THREAD

**Issue by daveraver** [manuelrn/Tvheadend_Movistar-Spain#1]
hola Manuel, vas a actualizar el script para crear la lista de canales con los cambios q va a haber los proximos meses? no van a ser muchos, pero seria util añadir/quitar canales q van a modificar la lista de canales. gracias, un saludo!

**Comment by manuelrn** [comment]
Hola buenas @daveraver, sí, por supuesto, la idea es ir actualizando tanto la lista de canales como sus respectivos logos según vaya habiendo nuevos cambios.

Hace bastante tiempo que no lo actualizo porque apenas han cambiado cuatro chorradas, nada serio.
De todas formas probablemente le de una vuelta en cuanto pueda y lo actualizo aunque tampoco haya cambiado mucho, aunque sea simplemente para darle al proyecto un poco de vidilla y que no parezca que está muerto.

Un saludo ;)

**Comment by daveraver** [comment]
ok muchas gracias Manuel, la verdad es que estoy encantado con tu script, una maravilla

saludos!!

**Comment by atarito** [comment]
Mientras use la raspberry como deco el script perfecto, pero ahora que estoy usando tvheadend con linux, más o menos, algunos picons, no los pone bien, también tengo un sintonizador tdt y cuando ejecuto el script me borra los canales, creo que voy a investigar y según y como le meta el tenedor al script con tu permiso :) igualmetne ¡muy buen trabajo!

**Comment by manuelrn** [comment]
Hola buenas de nuevo @daveraver, ya tienes la lista de canales actualizada hasta el día de hoy ;)

Si puedes pruébala y me cuentas que tal, y si me dices que está todo correcto pues cierro este issue.

**Comment by atarito** [comment]
Muchas gracias @manuelm

**Comment by daveraver** [comment]
Muchas gracias @manuelrn , me pillas retirado , a la vuelta pruebo con el nuevo script y comento, vamos, seguro que irá perfecto!! Saludos

**Comment by daveraver** [comment]
Hola Manuel, vienen mas cambios, mas canales se han añadido, y alguno mas que viene en septiembre. Como no podré probar hasta inicios del mes que viene, si sucedieran los cambios definitivos, podria esperar a la actualizacion completa, si no pruebo lo que hay ahora y luego se podrian actualizar los utlimos cambios y los que estan por venir en septiembre. Gracias!!!

**Comment by manuelrn** [comment]
Buenas de nuevo @daveraver, si, me imagino que te refieres a los canales `LaLiga 123 TV Multi 1`, `LaLiga 123 TV Multi 2` y `LaLiga 123 TV Multi 3`.

Si es así, ya los tengo añadidos a mi lista personal desde ayer, pero estoy esperando a que se realicen los logos de los mismos para poder publicar todo ello.

**Comment by daveraver** [comment]
Si, esos y el q van a empezar a emitir el mes q viene, canal de deportes 'Vamos', supuestamente inauguran en septiembre, fecha sin determinar. 
saludos y gracias!

**Comment by manuelrn** [comment]
Sí @daveraver, iré actualizando la lista según vea que vayan cambiando canales de la misma.
Acabo de actualizar la lista con los últimos cambios de ayer:

## 2018-08-25
### Añadidos nuevos canales
- LaLiga 123 TV Multi 1 (Dial: 176)
- LaLiga 123 TV Multi 2 (Dial: 177)
- LaLiga 123 TV Multi 3 (Dial: 178)

**Comment by daveraver** [comment]
Perfecto Manuel, muchas gracias y disculpa las molestias.

**Comment by daveraver** [comment]
Manuel, paso por aqui para agradecerte de nuevo el trabajo con tu script. Realmente muy util y efectivo. Espero q los q lo usan reporten si les fue a la perfeccion o tuvieron algun percance. 
un saludo y gracias!
