### ISSUE TITLE
sintaxis error linea 7

### ISSUE THREAD

**Issue by daveraver** [manuelrn/Tvheadend_Movistar-Spain#2]
Hola Manuel, finalmente he ejecutado el script y me da error en linea 7 en  libreelec en un meecol ki pro

LibreELEC:~ # ./Tvheadend_Movistar-Spain.sh -B
./Tvheadend_Movistar-Spain.sh: line 7: syntax error: unexpected newline
LibreELEC:~ # ./Tvheadend_Movistar-Spain.sh -b
./Tvheadend_Movistar-Spain.sh: line 7: syntax error: unexpected newline
LibreELEC:~ # ./Tvheadend_Movistar-Spain.sh -g

Espero se pueda solucionar facilmente o puede que esté haciendo algo mal aunque siempre hice lo mismo... ire probando... gracias un saludo

**Comment by daveraver** [comment]
al final era que no habia bajado el script corretamente, pero ahora sale esto,

LibreELEC:~/.kodi/addons/service.tvheadend42 # sh ./script.sh -b
: not found: line 10:
: not found: line 11: clear
./script.sh: line 70: syntax error: unexpected "elif" (expecting "then")

LibreELEC:~/.kodi/addons/service.tvheadend42 # sh script2.sh -b
script2.sh: line 44: syntax error: unexpected "|"

no entiendo que es lo que pasa, aunque es normal, de codigo, poca cosa puedo arreglar yo...

gracias, un saludo,

**Comment by manuelrn** [comment]
Buenas Daveraver, ¿el script ya lo habías utilizado alguna vez o es la primera vez que lo ejecutas?

Lo que quiero saber es si lo has usado alguna vez y antes te funcionaba bien pero ahora no te funciona (la misma versión del script), o si antes te funcionaba bien un script viejo pero el último script no te funciona, y en éste último caso saber si el script viejo te sigue funcionando (para saber si es culpa del script nuevo o culpa de tu sistema si antes iba bien y ahora mal).

Antes de nada, prueba a bajarte de nuevo el script y abriéndolo con un editor de texto comprueba que efectivamente es el script, lo digo porque no es la primera vez que alguien se descarga el código html de la web en vez del fichero del script en sí.
Una duda, ¿con el parámetro -g no te falla o también te falla? (lo digo porque indicas error con -B y -b, pero no con -g)
¿Sin poner ningún parámetro también te falla? (es decir, simplemente "./Tvheadend_Movistar-Spain.sh")



Necesito saber más datos, con eso no puedo ayudarte mucho más.

Lo único que puedo decirte es que en LibreELEC lo he probado yo mismo y también varias personas más y funcionaba perfectamente (lo probamos en su día, no ahora mismo, pero vaya que el script no ha cambiado y si iba antes en principio ahora irá exactamente igual).

Un saludo ;)

**Comment by daveraver** [comment]
Lo ejecuto desde la carpeta del addon de tvheadend, pero ejecutado en putty desde windows, otras veces lo he ejecutado y me sale el asistente con las preguntas de OS, y si kiero hacer backup luego instalar la lista canales nueva y picon... intentare ejecutarlo desde la carpeta del sistema, en meecol ki pro...

**Comment by manuelrn** [comment]
Tengo la sensación de que debes de tener mal el contenido del script, ¿como lo estás descargando?

Este es el enlace del script: https://github.com/manuelrn/Tvheadend_Movistar-Spain/raw/master/Tvheadend_Movistar-Spain.sh
Prueba en el navegador a hacer click derecho sobre este enlace de arriba, le das a "guardar como" y se te debería de descargar el fichero "Tvheadend_Movistar-Spain.sh".

Ya me vas diciendo ;)
Un saludo!

**Comment by daveraver** [comment]
efectivamente no descargaba bien el script, una vez descargado correctamente va bien. Antes de comer lo tuve listo, no unico que tuve que activar de nuevo el servicio de satelite del tuner en tvheadend y los picon no los coge, aunque la ruta de los picon en config general y en el canal salen asi, no los coge:

en general,
file:///storage/.kodi/userdata/addon_data/service.tvheadend42/Picons

y en cada canal sale,
picon://"service_code".png

service code segun cada canal....

tenia puestos permisos video:root en la carpeta Picons y lo cambié a video:1023 por que vi tb 1023 al tambien al fichero settings.xml de la carpeta service.tvheadend42.

Solo me quedaria el tema de los picon para redondear, epg va bien tambien,,,

saludos!

**Comment by daveraver** [comment]
Hola, lo curioso es que en tvhclient en libreelec no me muestra los picon del canal, y en la app TVHClient android/IOS si... no sé que tipo de bug debe haber en el libreelec que uso, es la version 8.x.
En fin Manuel, todo rodando excepto los picon que entiendo que algun problema hay con la distro que tengo instalada... porque no veo opcion en kodi de activar los picon en TVH de libreelec, no se si la hay...

**Comment by manuelrn** [comment]
Buenas de nuevo @daveraver, eso te iba a comentar ayer precisamente, que si en la interfaz web del Tvheadend, en el apartado "Guía" (donde salen todos los eventos de la EPG), si pulsas en el botón "i" (Información) en cualquiera de ellos se te abre una ventana, ¿en ella te sale correctamente los logos arriba a la derecha?

Si te salen ahí los logos, están bien puestos. Seguramente te salgan y los tengas bien ya que según indicas en las aplicaciones del teléfono móvil te salen correctamente.
<br/>
A otro compañero le pasó algo similar en LibreELEC, no había manera de que le salieran los logos (no es necesario activar nada en Kodi como indicas, los logos los muestra por defecto), probó mil cosas y nada... Al final, si no recuerdo mal, le tocó descargar los iconos y copiarlos manualmente en la memoria del dispositivo, y después poner los iconos a mano en Kodi (creo que se hace desde: Ajustes > Servicio PVR > Menú/OSD > Carpeta con iconos de canales).

No recuerdo si después de hacer eso en Kodi le tocó ir canal a canal seleccionando su icono en el propio Kodi, o si por el contrario antes de indicar la ruta en Kodi estuvo renombrando todos los ficheros de los logos poniéndole exactamente el mismo nombre que tiene el canal y después al seleccionar la carpeta en Kodi ya se mapeaban automáticamente... No lo recuerdo, se lo comentaré al compañero a ver si se puede pasar por aquí o decirme algo.

De todas formas es un coñazo porque te toca hacerlo a mano con cada canal y además pues cuando el script te actualice los logos y tal pues en Kodi no se actualizarán los cambios y tocará hacerlo a mano si quieres tenerlo al día.

**Comment by daveraver** [comment]
hola, gracias por tu explicacion, la verdad que es un poco jodido todo ese trabajo... lo dejare como esta, no merece la pena.
gracias por todo!!
