### ISSUE TITLE
EPG no descarga información

### ISSUE THREAD

**Issue by MPAndrew** [manuelrn/Tvheadend_Movistar-Spain#5]
Hola, ante todo muchas gracias por tu trabajo. El script funciona genial y hace muy fácil poner los canales sin estar toda la tarde ordenándolos uno por uno.

Tengo un problema y es que he ejecutado el script con la opción de instalar el grabber y bueno, el grabber funciona a medias: la epg aparece con la barra de progreso de cada canal, el nombre del programa en emisión y los picons; pero no aparece la información de cada programa. ¿Hay alguna solución para esto?

Muchas gracias de nuevo por tu trabajo.

**Comment by manuelrn** [comment]
Buenas, con mucho retraso pero finalmente hemos actualizado la lista de canales junto al grabber con una nueva EPG en condiciones, ya que como bien nos informaste la anterior EPG solamente reportaba el título de los eventos.

Un saludo!

**Comment by Erdk2** [comment]
Con la versión de tvheadend: version 4.2.8-36~g5bdcfd8ac parece que el grabber no funciona correctamente no detecta ninguna emisión

**Comment by manuelrn** [comment]
> Con la versión de tvheadend: version 4.2.8-36~g5bdcfd8ac parece que el grabber no funciona correctamente no detecta ninguna emisión

Os respondo en el otro Issue, en el nuevo que se ha abierto hoy.
