### ISSUE TITLE
No me crea services ni muxes y no se ven los canales

### ISSUE THREAD

**Issue by JulenGarciia** [manuelrn/Tvheadend_Movistar-Spain#6]
Ejecuto el script y no me genera los muxes ni los services
No se ve ningun canal
Estoy haciendo algo mal?

**Comment by manuelrn** [comment]
Hola buenas @iEzCnF,
¿Qué versión de Tvheadend utilizas?

Lo comento porque tiene pinta de ser eso.
En la versión 4.0.x (o anteriores) no funciona, se necesita la versión 4.1.x para arriba.

Comprueba que versión de Tvheadend tienes antes de nada.
Un saludo ;)

**Comment by JulenGarciia** [comment]
Vale tienes razon!
Gracias por la ayuda 😜
