### ISSUE TITLE
EPG vacía

### ISSUE THREAD

**Issue by brainstormi** [manuelrn/Tvheadend_Movistar-Spain#7]
El fichero guide.xml.gz aunque es actualizado a diario solo contiene información de eventos en días pasadas. El día 16 de Noviembre es el último día que refleja alguna entrada, por lo que la EPG en tvheadend aparece vacía a día de hoy.

**Comment by Erdk2** [comment]
Sí, me ha ocurrido igual, creí que era por la versión de Tvheadend, pero es eso que comentas

**Comment by manuelrn** [comment]
Gracias por avisar a ambos, @brainstormi y @Erdk2.

Esta mañana lo ha estado mirando y arreglando el compañero que se encarga de la EPG, y en principio ya consiguió dar con el problema y la volvió a poner a generar de 0.

Lo malo es que es un proceso lento y tardará unas horas, supongo que para mañana al mediodía ya se habrá terminado de generar por completo.
Mañana si os acordáis os agradecería si podéis volver a mirarlo y después pasaros por aquí a decir si ya sale bien o si sigue igual.

Gracias! ;)

**Comment by manuelrn** [comment]
@Erdk2 @brainstormi ya debería de estar funcionando la EPG, al final ha ido más rápido de lo esperado y ya terminó de generarse.

Si seguís sin EPG es porque todavía no ha llegado la hora a la que tengáis programado el Tvheadend que vuelva a ejecutar el grabber.

Así que si seguís sin EPG probad primero a forzar manualmente la ejecución del grabber:
Tvheadend > Configuración > Canales / EPG > Capturador de EPG > Volver a ejecutar los capturadores de EPG internos

Un saludo y ya confirmaréis para cerrar el Issue, gracias! ;)

**Comment by Erdk2** [comment]
Funciona bien! puedes cerrar el issue. Gracias!
